1. groupby
    특정 컬럼을 기준으로 그룹화하여 통계 연산을 수행하는 함수
2. pivot table
    엑셀의 피벗 테이블과 유사한 기능으로, 데이터를 그룹화하고 요약하는 함수
3. crosstab
    빈도 분석에 특화된 함수 / 자주 사용하진 않음

In [ ]:
import pandas as pd
import numpy as np

In [9]:
data1 = pd.read_csv('C:/Users/human/ku-python/data/treatment.csv')
data2 = pd.read_csv("C:/Users/human/ku-python/data/HM_all_stores.csv")

In [20]:
# Treatment자료에서 이름별 treatment의 평균계산
data1.groupby('name')['treatmenta'].mean()

name
Alice       46.704545
David       52.812500
Emma        48.071429
Isabella    51.660000
James       47.131579
John        47.740741
Michael     48.833333
Olivia      48.425000
Robert      51.594595
Sophia      48.163636
도윤          46.200000
민수          41.416667
서연          46.041667
수빈          55.229167
영희          46.588235
예진          48.782609
준호          42.450980
지연          56.146341
철수          47.767857
현우          47.867925
Name: treatmenta, dtype: float64

In [ ]:
# 여러 데이터값을 한번에보기
# data.groupby(그룹화할 컬럼)[집계할 컬럼].집계할 컬럼의 연산
data1.groupby('name').agg(['sum', 'mean', 'count', 'min', 'max'])

In [13]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C', 'C', 'B'],
    'Year': [2022, 2022, 2023, 2023, 2023, 2022, 2023, 2022],
    'Sales': [100, 150, 200, 250, 300, 250, 300, 100]
}

data = pd.DataFrame(data)
pd.pivot_table(data, values="Sales", index="Category", columns="Year", aggfunc="sum")

Year      2022  2023
Category
A          100   500
B          250   250
C          250   300

In [ ]:
data1.pivot_table(columns=['name'], values=['treatmenta', 'treatmentb'], aggfunc='mean', fill_value=0)

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C', 'C', 'B'],
    'Year': [2022, 2022, 2023, 2023, 2023, 2022, 2023, 2022],
    'Sales': [100, 150, 200, 250, 300, 250, 300, 100]
}

data = pd.DataFrame(data)

# margin - 현재까지 누적값을 계산해줌
pd.crosstab(index=data['Category'], columns=data['Year'], values=data['Sales'], aggfunc='sum', margins=True)

Year      2022  2023   All
Category
A          100   500   600
B          250   250   500
C          250   300   550
All        600  1050  1650

In [ ]:
# 기본 설정은 count - 값의 빈도수를 계산해줌
pd.crosstab(data['Category'], data['Year'])

Year      2022  2023
Category
A            1     2
B            2     1
C            1     1

In [24]:
# mutation_ID가 12000~12010사이 / patient_id를 기준으로 그룹화 후 score_a 평균

data = pd.read_csv("C:/Users/human/ku-python/data/pathogenicity_scores.csv")
filtered_data = data[(data['Mutation_ID'] >= 12000) & (data['Mutation_ID'] < 12011)]
filtered_data

       Patient_ID  Mutation_ID  LABEL  SCORE_A   SCORE_B   SCORE_C
13833          55        12000      0    0.853  0.632984  0.857330
13834          55        12001      0    0.853  0.632984  0.857330
13835          55        12002      0    0.853  0.632984  0.857330
13839          55        12003      0    0.074  0.010600  0.440473
13840          55        12004      0    0.147  0.034816  0.718837
13841          55        12005      1    0.710  0.976044  0.906924
13842          55        12006      0    0.030  0.163386  0.546290
13843          55        12007      0    0.030  0.168311  0.546290
13844          55        12008      0    0.896  0.239179  0.684880
13847          56        12009      0    0.230  0.765863  0.607796
13848          56        12010      0    0.168  0.771627  0.423602
28354         110        12006      0    0.030  0.163386  0.546290
28355         110        12007      0    0.030  0.168311  0.546290

In [23]:
filtered_data.pivot_table(index="Patient_ID", values="SCORE_A", aggfunc="mean")

            SCORE_A
Patient_ID
55            0.494
56            0.199
110           0.030

=========================================================================================================
파일 저장 -> to_형식
pd.to_csv
pd.to_excel

In [28]:
# 기본적으로 인덱싱 포함
filtered_data.to_csv('test.csv', encoding='utf-8')

In [ ]:
# 인덱스 미포함
filtered_data.to_csv('test2.csv', encoding='utf-8', index=False)