In [1]:
import pandas as pd
import numpy as np

In [12]:
data = pd.read_csv('c:/Users/human/ku-python/data/amazon.csv')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

In [14]:
data.loc[data['rating'] == "|", 'rating'] = '0'

In [15]:
data.loc[data['rating'] == "|"]

Empty DataFrame
Columns: [product_id, product_name, category, discounted_price, actual_price, discount_percentage, rating, rating_count, about_product, user_id, user_name, review_id, review_title, review_content, img_link, product_link]
Index: []

In [16]:
data.replace({"|": 0})
data['rating'] = data['rating'].astype('float32')

In [19]:
data['rating_count'] = data['rating_count'].fillna('0')

In [20]:
data['rating_count'] = data['rating_count'].str.replace(",", "").astype('int32')

In [27]:
filtered_data = data[data['rating'] >= 4.5]

In [30]:
filtered_data[['product_id', 'product_name', 'rating', 'rating_count']].sort_values(by='rating_count', ascending=False).head(5)

,product_id,product_name,rating,rating_count
864,B09X7DY7Q4,SanDisk Extreme SD UHS I 64GB Card for 4K Vide...,4.5,205052
40,B00NH11KIK,AmazonBasics USB 2.0 Cable - A-Male to B-Male ...,4.5,107687
852,B00NH11KIK,AmazonBasics USB 2.0 Cable - A-Male to B-Male ...,4.5,107686
810,B07G3YNLJB,Crucial BX500 240GB 3D NAND SATA 6.35 cm (2.5-...,4.5,92925
212,B00NH13Q8W,AmazonBasics USB 2.0 Extension Cable for Perso...,4.5,74977